#!/usr/bin/env bash

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"

SOURCE_FILE="${REPO_ROOT}/.claude/skills/author-profile/PROFILE.md"
TARGET_FILE="${REPO_ROOT}/_tabs/about.md"
TMP_FILE="$(mktemp)"

cleanup() {
  rm -f "${TMP_FILE}"
}

trap cleanup EXIT

if [[ ! -f "${SOURCE_FILE}" ]]; then
  echo "source file not found: ${SOURCE_FILE}" >&2
  exit 1
fi

{
  cat <<'EOF'
---
title: 关于我
permalink: /about/
icon: fas fa-info-circle
order: 4
---

<!-- This file is generated by scripts/sync_author_profile_page.sh. -->

> 这是博客的 About 页面，不是博客文章。
>
> 内容源文件是 `.claude/skills/author-profile/PROFILE.md`，由 `author-profile` skill 和 agent 维护；站点构建前会自动同步到这里。

EOF

  awk 'NR == 1 && $0 == "# 作者画像" { next } { print }' "${SOURCE_FILE}"

  cat <<'EOF'

小入口：[角落](/corner/)。那里放了一些面试记录和碎碎念，不进主导航。
EOF
} > "${TMP_FILE}"

if [[ -f "${TARGET_FILE}" ]] && cmp -s "${TMP_FILE}" "${TARGET_FILE}"; then
  chmod 644 "${TARGET_FILE}"
  exit 0
fi

mv "${TMP_FILE}" "${TARGET_FILE}"
chmod 644 "${TARGET_FILE}"
